repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
  -   repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
      - id: flake8
  -   repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
      -   id: isort
  # -   repo: https://github.com/PyCQA/pylint
  #     rev: v2.14.5
  #     hooks:
  #     -   id: pylint
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      # args:
      #   [
      #     "-rn", # Only display messages
      #     "-sn", # Don't display the score
      #   ]
  -   repo: https://github.com/econchick/interrogate
      rev: 1.5.0
      hooks:
      - id: interrogate
        args: [-vv, -i, --fail-under=80]
